import type { PilotSlug } from './config';
import type { Sale, StockItem } from './types';

/**
 * Fictional seed data for the three sales-demo pilots (see config.ts,
 * DEMO_PILOT_SLUGS). Used two ways:
 *  1. As the initial value for the 'items'/'sales' persisted state on first
 *     load of a demo pilot (see App.tsx).
 *  2. As what "Reset to demo data" in Settings restores — since resetting
 *     just clears this pilot's localStorage keys and reloads, the app picks
 *     these same seeds back up as the initial value again.
 * Never touched by, or linked to, any real pilot's data — each demo has its
 * own storage namespace like any other PILOT_SLUG.
 */
export interface DemoSeed {
  items: StockItem[];
  sales: Sale[];
}

const now = Date.now();
const day = 86400000;

// demo-fashion — mirrors Jhum Fashion: clothing/textile, bundle-bought
// stock, BDT pricing for a Bangladeshi diaspora audience.
const demoFashionItems: StockItem[] = [
  {
    id: 'df1',
    name: 'Cotton batik three-piece',
    category: 'Three-piece',
    quantity: 12,
    purchasePrice: 650,
    salePrice: 1450,
    supplier: 'Karwan Bazar wholesale',
    tags: ['bestseller', 'daily wear'],
    environment: 'S–XL, or free size',
    channels: [
      { id: 'c1', name: 'Facebook Marketplace', price: 1450 },
      { id: 'c2', name: 'WhatsApp', price: 1400 },
    ],
    aging: false,
    soldOut: false,
    createdAt: now - day * 2,
  },
  {
    id: 'df2',
    name: 'Georgette embroidered three-piece',
    category: 'Three-piece',
    quantity: 6,
    purchasePrice: 1200,
    salePrice: 2600,
    supplier: 'Karwan Bazar wholesale',
    tags: ['festive'],
    environment: 'S–XL',
    channels: [{ id: 'c1', name: 'Instagram', price: 2600 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 6,
  },
  {
    id: 'df3',
    name: 'Jamdani saree',
    category: 'Saree',
    quantity: 4,
    purchasePrice: 3500,
    salePrice: 6500,
    supplier: 'Local weaver, Narayanganj',
    tags: ['festive', 'handloom'],
    environment: 'Jamdani',
    channels: [{ id: 'c1', name: 'WhatsApp', price: 6500 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 10,
  },
  {
    id: 'df4',
    name: 'Katan silk saree',
    category: 'Saree',
    quantity: 2,
    purchasePrice: 4200,
    salePrice: 8000,
    tags: ['premium'],
    environment: 'Katan',
    channels: [{ id: 'c1', name: 'Instagram', price: 8000 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 15,
  },
  {
    id: 'df5',
    name: 'Printed kurti',
    category: 'Kurti',
    quantity: 20,
    purchasePrice: 320,
    salePrice: 750,
    tags: ['casual'],
    environment: 'S–XL, or free size',
    channels: [
      { id: 'c1', name: 'Facebook Marketplace', price: 750 },
      { id: 'c2', name: 'Instagram', price: 750 },
    ],
    aging: false,
    soldOut: false,
    createdAt: now - day * 4,
  },
  {
    id: 'df6',
    name: 'Linen two-piece',
    category: 'Two-piece',
    quantity: 8,
    purchasePrice: 700,
    salePrice: 1550,
    tags: ['summer'],
    channels: [{ id: 'c1', name: 'WhatsApp', price: 1550 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 8,
  },
  {
    id: 'df7',
    name: 'Cotton fabric, per metre',
    category: 'Fabric',
    quantity: 40,
    purchasePrice: 180,
    salePrice: 320,
    tags: ['by the metre'],
    environment: '44 inch width, sold per metre',
    channels: [{ id: 'c1', name: 'Physical market', price: 320 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 12,
  },
  {
    id: 'df8',
    name: 'Embroidered clutch bag',
    category: 'Accessories',
    quantity: 15,
    purchasePrice: 150,
    salePrice: 400,
    tags: ['gift'],
    channels: [{ id: 'c1', name: 'Instagram', price: 400 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 5,
  },
  {
    id: 'df9',
    name: 'Eid-special three-piece',
    category: 'Three-piece',
    quantity: 0,
    purchasePrice: 900,
    salePrice: 1900,
    tags: ['festive', 'eid'],
    channels: [{ id: 'c1', name: 'Facebook Marketplace', price: 1900 }],
    aging: false,
    soldOut: true,
    createdAt: now - day * 20,
  },
  {
    id: 'df10',
    name: 'Winter shawl',
    category: 'Accessories',
    quantity: 5,
    purchasePrice: 280,
    salePrice: 350,
    tags: ['seasonal'],
    channels: [{ id: 'c1', name: 'Physical market', price: 350 }],
    aging: true,
    soldOut: false,
    createdAt: now - day * 45,
    // Already marked down once the season passed — matches what
    // handleAgingMarkdown in App.tsx does when a seller picks "Markdown".
    agingAction: 'markdown',
    agingActionNote: 'Marked down from ৳550 — out of season, clearing before next winter',
  },
];

const demoFashionSales: Sale[] = [
  {
    id: 'dfs1',
    date: now - day * 1,
    lines: [{ itemId: 'df9', name: 'Eid-special three-piece', quantity: 3, unitPrice: 1900 }],
    total: 5700,
    channelName: 'Facebook Marketplace',
  },
  {
    id: 'dfs2',
    date: now - day * 2,
    lines: [
      { itemId: 'df1', name: 'Cotton batik three-piece', quantity: 2, unitPrice: 1450 },
      { itemId: 'df5', name: 'Printed kurti', quantity: 3, unitPrice: 750 },
    ],
    total: 5150,
    channelName: 'WhatsApp',
  },
];

// demo-craft — mirrors Tahmina/Shoilee: handmade jewellery, several
// material parts per product (matches the cost-part calculator), BDT.
const demoCraftItems: StockItem[] = [
  {
    id: 'dc1',
    name: 'Brass filigree earrings',
    category: 'Jewellery',
    quantity: 15,
    purchasePrice: 180,
    salePrice: 450,
    tags: ['handmade', 'brass'],
    environment: 'Brass wire, glass beads',
    channels: [{ id: 'c1', name: 'Instagram', price: 450 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 3,
  },
  {
    id: 'dc2',
    name: 'Beaded choker necklace',
    category: 'Jewellery',
    quantity: 8,
    purchasePrice: 220,
    salePrice: 600,
    tags: ['handmade'],
    environment: 'Glass beads, brass clasp, cotton cord',
    channels: [{ id: 'c1', name: 'Facebook Marketplace', price: 600 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 7,
  },
  {
    id: 'dc3',
    name: 'Freshwater pearl bracelet',
    category: 'Jewellery',
    quantity: 10,
    purchasePrice: 150,
    salePrice: 380,
    tags: ['pearl'],
    environment: 'Freshwater pearl, silver-plated clasp',
    channels: [{ id: 'c1', name: 'Instagram', price: 380 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 5,
  },
  {
    id: 'dc4',
    name: 'Terracotta drop earrings',
    category: 'Jewellery',
    quantity: 25,
    purchasePrice: 60,
    salePrice: 180,
    tags: ['terracotta', 'lightweight'],
    channels: [
      { id: 'c1', name: 'Instagram', price: 180 },
      { id: 'c2', name: 'Physical market', price: 170 },
    ],
    aging: false,
    soldOut: false,
    createdAt: now - day * 9,
  },
  {
    id: 'dc5',
    name: 'Macrame wall hanging',
    category: 'Home & Décor',
    quantity: 6,
    purchasePrice: 300,
    salePrice: 750,
    tags: ['handmade'],
    environment: '40cm x 60cm',
    channels: [{ id: 'c1', name: 'Facebook Marketplace', price: 750 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 11,
  },
  {
    id: 'dc6',
    name: 'Hand-painted clay vase',
    category: 'Home & Décor',
    quantity: 4,
    purchasePrice: 250,
    salePrice: 650,
    tags: ['handmade'],
    environment: '18cm tall',
    channels: [{ id: 'c1', name: 'Instagram', price: 650 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 14,
  },
  {
    id: 'dc7',
    name: 'Beaded anklet set',
    category: 'Jewellery',
    quantity: 12,
    purchasePrice: 90,
    salePrice: 250,
    tags: ['set of 2'],
    channels: [{ id: 'c1', name: 'Instagram', price: 250 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 4,
  },
  {
    id: 'dc8',
    name: 'Embroidered coin purse',
    category: 'Accessories',
    quantity: 18,
    purchasePrice: 70,
    salePrice: 200,
    tags: ['gift'],
    channels: [{ id: 'c1', name: 'Physical market', price: 200 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 6,
  },
  {
    id: 'dc9',
    name: 'Bridal jewellery set',
    category: 'Jewellery',
    quantity: 0,
    purchasePrice: 1200,
    salePrice: 2800,
    tags: ['bridal', 'made to order'],
    channels: [{ id: 'c1', name: 'Instagram', price: 2800 }],
    aging: false,
    soldOut: true,
    createdAt: now - day * 25,
  },
  {
    id: 'dc10',
    name: 'Rakhi bracelet set',
    category: 'Jewellery',
    quantity: 7,
    purchasePrice: 40,
    salePrice: 120,
    tags: ['seasonal', 'festival'],
    channels: [{ id: 'c1', name: 'Physical market', price: 100 }],
    aging: true,
    soldOut: false,
    createdAt: now - day * 60,
    // Already handled — bundled into a discounted set once the festival
    // passed, matches what handleAgingBundle does when "Bundle" is picked.
    agingAction: 'bundle',
    agingActionNote: 'Bundled 3-for-1 to clear post-festival leftover stock',
  },
];

const demoCraftSales: Sale[] = [
  {
    id: 'dcs1',
    date: now - day * 1,
    lines: [{ itemId: 'dc9', name: 'Bridal jewellery set', quantity: 1, unitPrice: 2800 }],
    total: 2800,
    channelName: 'Instagram',
  },
  {
    id: 'dcs2',
    date: now - day * 3,
    lines: [
      { itemId: 'dc1', name: 'Brass filigree earrings', quantity: 4, unitPrice: 450 },
      { itemId: 'dc4', name: 'Terracotta drop earrings', quantity: 5, unitPrice: 180 },
    ],
    total: 2700,
    channelName: 'Facebook Marketplace',
  },
];

// demo-food — mirrors Maliha/Moja: small-batch food & drink, EUR pricing.
const demoFoodItems: StockItem[] = [
  {
    id: 'dm1',
    name: 'Chilli garlic oil, 250ml',
    category: 'Food & Drink',
    quantity: 24,
    purchasePrice: 2.2,
    salePrice: 6.5,
    tags: ['spicy', 'bestseller'],
    environment: 'Keep refrigerated, best within 3 weeks',
    channels: [{ id: 'c1', name: 'Instagram', price: 6.5 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 2,
  },
  {
    id: 'dm2',
    name: 'Mango chutney, 300g jar',
    category: 'Food & Drink',
    quantity: 18,
    purchasePrice: 1.8,
    salePrice: 5,
    tags: ['sweet'],
    environment: 'Store in a cool dry place, refrigerate after opening',
    channels: [{ id: 'c1', name: 'Facebook Marketplace', price: 5 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 6,
  },
  {
    id: 'dm3',
    name: 'Rose & cardamom syrup',
    category: 'Food & Drink',
    quantity: 10,
    purchasePrice: 3.5,
    salePrice: 9,
    tags: ['drinks'],
    channels: [{ id: 'c1', name: 'Instagram', price: 9 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 9,
  },
  {
    id: 'dm4',
    name: 'Homemade ginger tea blend',
    category: 'Food & Drink',
    quantity: 30,
    purchasePrice: 1.2,
    salePrice: 4,
    tags: ['tea'],
    channels: [{ id: 'c1', name: 'Physical market', price: 4 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 4,
  },
  {
    id: 'dm5',
    name: 'Spiced pickled lime',
    category: 'Food & Drink',
    quantity: 15,
    purchasePrice: 2,
    salePrice: 5.5,
    tags: ['tangy'],
    environment: 'Store in a cool dry place',
    channels: [{ id: 'c1', name: 'Instagram', price: 5.5 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 8,
  },
  {
    id: 'dm6',
    name: 'Turmeric & black pepper honey',
    category: 'Food & Drink',
    quantity: 12,
    purchasePrice: 4,
    salePrice: 10,
    tags: ['wellness'],
    channels: [{ id: 'c1', name: 'Facebook Marketplace', price: 10 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 13,
  },
  {
    id: 'dm7',
    name: 'Coconut chilli sambal',
    category: 'Food & Drink',
    quantity: 20,
    purchasePrice: 2.5,
    salePrice: 6,
    tags: ['spicy'],
    channels: [{ id: 'c1', name: 'Instagram', price: 6 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 5,
  },
  {
    id: 'dm8',
    name: 'Fermented chilli paste',
    category: 'Food & Drink',
    quantity: 16,
    purchasePrice: 2.1,
    salePrice: 5.8,
    tags: ['fermented', 'spicy'],
    channels: [{ id: 'c1', name: 'Physical market', price: 5.8 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 7,
  },
  {
    id: 'dm9',
    name: 'Limited-batch plum jam',
    category: 'Food & Drink',
    quantity: 0,
    purchasePrice: 2.8,
    salePrice: 7.5,
    tags: ['limited batch'],
    channels: [{ id: 'c1', name: 'Instagram', price: 7.5 }],
    aging: false,
    soldOut: true,
    createdAt: now - day * 18,
  },
  {
    id: 'dm10',
    name: 'Diwali spice gift box',
    category: 'Food & Drink',
    quantity: 6,
    purchasePrice: 6,
    salePrice: 14,
    tags: ['seasonal', 'gift'],
    channels: [{ id: 'c1', name: 'Physical market', price: 12 }],
    aging: true,
    soldOut: false,
    createdAt: now - day * 50,
    // Already handled — held back for next year's gifting season rather
    // than marked down or donated, matches what handleAgingOther does.
    agingAction: 'other',
    agingActionNote: 'Held back — repackaging for next Diwali rather than clearing now',
  },
];

const demoFoodSales: Sale[] = [
  {
    id: 'dms1',
    date: now - day * 1,
    lines: [{ itemId: 'dm9', name: 'Limited-batch plum jam', quantity: 8, unitPrice: 7.5 }],
    total: 60,
    channelName: 'Instagram',
  },
  {
    id: 'dms2',
    date: now - day * 4,
    lines: [
      { itemId: 'dm1', name: 'Chilli garlic oil, 250ml', quantity: 6, unitPrice: 6.5 },
      { itemId: 'dm4', name: 'Homemade ginger tea blend', quantity: 4, unitPrice: 4 },
    ],
    total: 55,
    channelName: 'Physical market',
  },
];

export const DEMO_SEEDS: Partial<Record<PilotSlug, DemoSeed>> = {
  'demo-fashion': { items: demoFashionItems, sales: demoFashionSales },
  'demo-craft': { items: demoCraftItems, sales: demoCraftSales },
  'demo-food': { items: demoFoodItems, sales: demoFoodSales },
};
