import type { StockItem } from './types';

const now = Date.now();
const day = 86400000;

// Demo data for Flowertot Botanicals — a houseplant reseller, not a cut-flower
// or produce shop. The previous version of this file (roses, tulips, basil,
// vine tomatoes) was leftover from an earlier generic-florist scaffold and
// didn't match the pilot's actual business. Species and care notes below are
// drawn from common UK houseplant retail stock (Hortology, RHS) so the demo
// reads as genuinely representative rather than placeholder text.
export const mockItems: StockItem[] = [
  {
    id: '1',
    name: 'Monstera deliciosa — Swiss cheese plant',
    category: 'Foliage',
    quantity: 6,
    purchasePrice: 9,
    salePrice: 25,
    supplier: 'Hortology wholesale',
    tags: ['popular', 'statement'],
    environment: 'Bright indirect light, water weekly',
    channels: [
      { id: 'c1', name: 'Instagram', price: 25 },
      { id: 'c2', name: 'Shop', price: 28 },
    ],
    aging: false,
    soldOut: false,
    createdAt: now - day * 1,
  },
  {
    id: '2',
    name: 'Epipremnum aureum — Golden pothos',
    category: 'Trailing & Climbing',
    quantity: 0,
    purchasePrice: 5,
    salePrice: 12,
    supplier: 'Local grower',
    tags: ['beginner-friendly'],
    channels: [{ id: 'c1', name: 'Instagram', price: 12 }],
    aging: false,
    soldOut: true,
    createdAt: now - day * 14,
  },
  {
    id: '3',
    name: 'Sansevieria trifasciata — Snake plant',
    category: 'Foliage',
    quantity: 18,
    purchasePrice: 8,
    salePrice: 20,
    supplier: 'Local grower',
    tags: ['low-maintenance', 'air-purifying'],
    environment: 'Tolerates low light, water sparingly',
    channels: [{ id: 'c1', name: 'Shop', price: 20 }],
    aging: true,
    soldOut: false,
    createdAt: now - day * 9,
  },
  {
    id: '4',
    name: 'Opuntia microdasys — Bunny ear cactus',
    category: 'Succulents & Cacti',
    quantity: 32,
    purchasePrice: 4,
    salePrice: 10,
    supplier: 'Local grower',
    tags: ['pet-caution'],
    environment: 'Full sun, water sparingly',
    channels: [
      { id: 'c1', name: 'Instagram', price: 10 },
      { id: 'c2', name: 'Shop', price: 11 },
    ],
    aging: false,
    soldOut: false,
    createdAt: now - day * 3,
  },
  {
    id: '5',
    name: 'Chamaedorea elegans — Parlour palm',
    category: 'Palms',
    quantity: 7,
    purchasePrice: 6,
    salePrice: 18,
    supplier: 'Hortology wholesale',
    tags: ['pet-friendly', 'shade-loving'],
    channels: [{ id: 'c1', name: 'Instagram', price: 18 }],
    aging: true,
    soldOut: false,
    createdAt: now - day * 21,
  },
  {
    id: '6',
    name: 'Small terracotta pots',
    category: 'Accessories',
    quantity: 50,
    purchasePrice: 2,
    salePrice: 8,
    tags: ['gift'],
    channels: [{ id: 'c1', name: 'Shop', price: 8 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 5,
  },
];
