import type { StockItem } from './types';

const now = Date.now();
const day = 86400000;

export const mockItems: StockItem[] = [
  {
    id: '1',
    name: 'White roses',
    category: 'Flowers',
    quantity: 40,
    purchasePrice: 80,
    salePrice: 250,
    supplier: 'Columbia Road Market',
    tags: ['wedding', 'winter'],
    environment: 'Cool, 4°C',
    channels: [
      { id: 'c1', name: 'Instagram', price: 250 },
      { id: 'c2', name: 'Shop', price: 270 },
    ],
    aging: false,
    soldOut: false,
    createdAt: now - day * 1,
  },
  {
    id: '2',
    name: 'Red tulips',
    category: 'Flowers',
    quantity: 0,
    purchasePrice: 45,
    salePrice: 140,
    supplier: 'Holland Import',
    tags: ['spring'],
    channels: [{ id: 'c1', name: 'Instagram', price: 140 }],
    aging: false,
    soldOut: true,
    createdAt: now - day * 14,
  },
  {
    id: '3',
    name: 'Basil pot',
    category: 'Herbs',
    quantity: 18,
    purchasePrice: 25,
    salePrice: 79,
    supplier: 'Local grower',
    tags: ['organic'],
    environment: 'Sunny, humid',
    channels: [{ id: 'c1', name: 'Shop', price: 79 }],
    aging: true,
    soldOut: false,
    createdAt: now - day * 9,
  },
  {
    id: '4',
    name: 'Vine tomatoes',
    category: 'Vegetables',
    quantity: 32,
    purchasePrice: 30,
    salePrice: 95,
    supplier: 'Local grower',
    tags: ['seasonal'],
    channels: [
      { id: 'c1', name: 'Instagram', price: 95 },
      { id: 'c2', name: 'Shop', price: 99 },
    ],
    aging: false,
    soldOut: false,
    createdAt: now - day * 3,
  },
  {
    id: '5',
    name: 'Eucalyptus bunch',
    category: 'Flowers',
    quantity: 7,
    purchasePrice: 60,
    salePrice: 189,
    supplier: 'Columbia Road Market',
    tags: ['dried', 'autumn'],
    channels: [{ id: 'c1', name: 'Instagram', price: 189 }],
    aging: true,
    soldOut: false,
    createdAt: now - day * 21,
  },
  {
    id: '6',
    name: 'Small baskets',
    category: 'Accessories',
    quantity: 50,
    purchasePrice: 15,
    salePrice: 65,
    tags: ['gift'],
    channels: [{ id: 'c1', name: 'Shop', price: 65 }],
    aging: false,
    soldOut: false,
    createdAt: now - day * 5,
  },
];
